language: node_js
node_js:
- 14.0.0
after_success:
- bash ./build.sh
env:
  global:
  - secure: py/KvDNlQN5Yc5aRzNbdFJLaRiwmcFv/cIrLMJHOTqvtdt0eLr1XltLx4yQDtKDizJkaptAvKoN9L89GWqevFJZa+2v1Kd6SkylxDrkp4GJ9y0QZjyKUOL5HgdWqDBloMVk3GSWooAt+Kde978tjaDZ05L3wYN2QQ63NhasbNrk=
  - secure: ByJ1YDEs/+hircineTQHZ4sYJ/Yxo/JRZRRGn3McutFd+XFVNKzX421B3/fB12piFyHoxN/5AMuzOAW9V+mfs092IWqSl0LwXQqUq7jc+vqB3OtyNeRPA1Y85P/v/xlp/JYEgnWSDX1rveXYAthGwSfDKNqx0vSqK9Edk1nr/bQ=
